version: '3.4'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    links:
      - web
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./assets:/var/www/html/web/assets
      - web:/var/www/html

  web:
    image: craftcms
    build: .
    links:
      - postgres
      - redis
    volumes:
      - ./templates:/var/www/html/templates
      - web:/var/www/html
    environment:
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis

      DB_SERVER: postgres
      DB_NAME: craft
      DB_USER: craft
      DB_PASSWORD: secret
      DB_DATABASE: craft
      DB_SCHEMA: public
      DB_DRIVER: pgsql
      DB_PORT: 5432
      DB_TABLE_PREFIX: ut

  postgres:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_USER: craft
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: craft
    volumes:
      # Persistent data
      - data:/var/lib/postgresql

  redis:
    image: redis:4-alpine
    volumes:
      - data:/data

volumes:
  data:
  web:
